Sales employee branch2
UserConor/CCCS-GO pull request #5
Opened 2023-10-11 14:03 UTC by Criofann

Added the getSalesEmployeeByID function to the salesEmployeeDAO

2023-10-11 14:07 UTC, BlankAmber requested changes
Class names should be upper camel case with the first letter capitalised too 😡 💢

2023-10-11 14:11 UTC, BlankAmber approved these changes
The most sublime code I've ever witnessed

2023-10-11 14:16 UTC, BlankAmber requested changes
Wait there's no Service or Controller class

2023-10-11 14:48 UTC, BlankAmber commented
This PR implements task 10

2023-10-11 14:55 UTC, BlankAmber approved these changes

2023-10-12 09:51 UTC, jkelso662 requested changes
Very good! Needed a better pull request description to tell me what feature/backlog item this is completing/related to. One aspect isn't implemented by the looks of things so if completed - this would look good :)

2023-10-12 09:51 UTC, jkelso662 commented on src/main/java/org/kainos/ea/client/InvalidSalesEmployeeException.java
> +        super(validation);
Is there a reason you are only calling the exception function here with super instead of using your own more useful error message?

2023-10-12 09:51 UTC, jkelso662 commented on src/main/java/org/kainos/ea/core/SalesEmployeeValidator.java
> +        return null;
This doesn't look implemented. Is the solution here missing?

2023-10-12 10:00 UTC, jkelso662 commented on src/main/java/org/kainos/ea/client/InvalidSalesEmployeeException.java
> +        super(validation);
Ignore this. Validation string has the error message!

2023-10-12 10:41 UTC, lullabelle approved these changes
ok im approving. but you need to reference the placeholder in the pull request description!

2023-10-12 10:42 UTC, lullabelle approved these changes

2023-10-12 11:12 UTC, jkelso662 approved these changes

2023-10-12 11:24 UTC, merged