Task4
UserConor/CCCS-GO pull request #6
Opened 2023-10-11 14:51 UTC by UserConor

- Added the ability to view delivery employees from API.

2023-10-11 15:05 UTC, BlankAmber approved these changes

2023-10-11 15:06 UTC, BlankAmber commented
EXCELLENT WORK CONOR !!

2023-10-12 09:56 UTC, jkelso662 requested changes
Main thing here is that your exceptions aren't extending the same things compared to others in the repo. If there is a specific reason for this then justify them in the comments. Only other thing to note here is that there are a few places where there is too much extra white space. Not a blocker but might as well sort when covering above :)

2023-10-12 09:56 UTC, jkelso662 commented on src/main/java/org/kainos/ea/DropwizardWebServiceApplication.java
>          // TODO: implement application
This will be removed in an earlier pull request. Make sure to pull in latest from main once these have been merged in.

2023-10-12 09:56 UTC, jkelso662 commented on src/main/java/org/kainos/ea/client/FailedToGetDeliveryEmployeesException.java
> +public class FailedToGetDeliveryEmployeesException extends Throwable {
Some of your team's exceptions are extending Throwable, some Exception. I think yous need to make this consistent.

2023-10-12 10:51 UTC, jkelso662 approved these changes
Fab

2023-10-12 10:52 UTC, merged